run:
  timeout: 5m
  tests: false
  skip-dirs:
    - vendor
    - third_party

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-blank: false

issues:
  exclude-use-default: true
  exclude-rules:
    # Exclude error checks in test files
    - path: _test\.go
      linters:
        - errcheck
        - staticcheck