# golangci-lint v2 configuration
version: "2"

run:
  timeout: 5m
  tests: false  # Don't analyze test files

linters:
  enabled:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: true