name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run tests
      run: go test -v ./...

    - name: Build all platforms
      run: make build-all

    - name: Create checksums
      run: |
        cd dist
        sha256sum * > checksums.txt
        cat checksums.txt

    - name: Extract release notes
      id: extract-release-notes
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/claude-code-proxy-*
          dist/checksums.txt
        generate_release_notes: true
        body: |
          ## Installation

          Download the appropriate binary for your platform:

          ### macOS (Apple Silicon)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.extract-release-notes.outputs.version }}/claude-code-proxy-darwin-arm64
          chmod +x claude-code-proxy-darwin-arm64
          sudo mv claude-code-proxy-darwin-arm64 /usr/local/bin/claude-code-proxy
          ```

          ### macOS (Intel)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.extract-release-notes.outputs.version }}/claude-code-proxy-darwin-amd64
          chmod +x claude-code-proxy-darwin-amd64
          sudo mv claude-code-proxy-darwin-amd64 /usr/local/bin/claude-code-proxy
          ```

          ### Linux (x86_64)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.extract-release-notes.outputs.version }}/claude-code-proxy-linux-amd64
          chmod +x claude-code-proxy-linux-amd64
          sudo mv claude-code-proxy-linux-amd64 /usr/local/bin/claude-code-proxy
          ```

          ### Linux (ARM64)
          ```bash
          wget https://github.com/${{ github.repository }}/releases/download/${{ steps.extract-release-notes.outputs.version }}/claude-code-proxy-linux-arm64
          chmod +x claude-code-proxy-linux-arm64
          sudo mv claude-code-proxy-linux-arm64 /usr/local/bin/claude-code-proxy
          ```

          ### Windows
          Download `claude-code-proxy-windows-amd64.exe` and add to your PATH.

          ## Verify Installation
          ```bash
          claude-code-proxy --help
          ```

          ## Quick Start
          See [README.md](https://github.com/${{ github.repository }}#quick-start) for configuration instructions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
